### ISSUE TITLE
problem for enabling file

### ISSUE THREAD

**Issue by fzh-adham** [analogdevicesinc/ai8x-training#319]
Hi 
I want to enable distiller in training part for training here and I couldn't find a suitable command for it please guide me.
thanks a lot

**Comment by rotx-maxim** [comment]
Can yo provide more detail about your network and the task you're trying to accomplish?

**Comment by fzh-adham** [comment]
Surely
For distillation methods
Such as pruning

**Comment by rotx-maxim** [comment]
MAX78000/MAX78002 only support channel based pruning. Is this what you're attempting to do? Distiller is not used for that functionality on MAX7800X.

**Comment by fzh-adham** [comment]
Thanks for reply
What do u mean with channel pruning?
I want to use compress methods for weights ...
It means that I can't use pruning??

**Comment by fzh-adham** [comment]
could you please help me about channel based pruning? how can I use it for training?
I would appreciate if you help me

**Comment by rotx-maxim** [comment]
You can manually reduce the number of channels for your layers. To automate this, you would use the NAS.
Perhaps you can describe your project and what you are trying to achieve with MAX7800X in more detail so we can assist better. Feel free to contact us using processors.support@analog.com if you don't want to publicly share that information in this thread.

**Comment by fzh-adham** [comment]
thanks a lot for this opportunity 
I have sent you message recently and I have been waiting for your reply.
